#!/usr/bin/env python3
"""Install Open Graph + twitter:card tags on every page. Idempotent.

Mirrors add_ga4_events.py: one generated block per page, delimited by markers,
replaced wholesale on re-run rather than stacked. Page list is auto-discovered,
so adding a page and re-running is the whole workflow.

Values are NOT invented. og:title / og:description are copied verbatim from the
page's existing <title> and <meta name="description">; og:url from its canonical.
If a page is missing any of those, it is reported and skipped -- the fix is to
add the real tag, not to let this script guess.

og:image points at real 1456x822 art that ships in the repo. It is NOT the
ideal 1200x630; that is a known, recorded compromise (see SEO-NOTES.md).
target-digital-logo.png must never be used here -- at 182x88 it is under
Facebook's 200px floor and renders as the grey box the tag exists to prevent.

Usage:  py add_og_tags.py           install / refresh
        py add_og_tags.py --check   exit 1 if any page is missing or stale
"""
import glob
import io
import re
import sys

SITE = "https://targetdigital.com.au"
START = "<!-- og:start - generated by add_og_tags.py; edit the script, not this block -->"
END = "<!-- og:end -->"

# Only two hero images are in active use on pages; both are 1456x822.
IMG_DEFAULT = "funnel-hero.png"
IMG_BY_PAGE = {
    "outbound.html": "outbound-hero.png",
    "lead-magnet-outbound.html": "outbound-hero.png",
    "outboundcalldemo.html": "outbound-hero.png",
}
IMG_W, IMG_H = "1456", "822"


def extract(src, path):
    """Pull the three values OG needs. Returns (title, desc, url) or None."""
    title = re.search(r"<title>(.*?)</title>", src, re.S)
    desc = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', src)
    canon = re.search(r'<link\s+rel="canonical"\s+href="([^"]+)"', src)
    missing = [n for n, m in
               (("title", title), ("description", desc), ("canonical", canon))
               if not m]
    if missing:
        print("  SKIP %s: missing %s" % (path, ", ".join(missing)))
        return None
    return title.group(1).strip(), desc.group(1).strip(), canon.group(1).strip()


def dominant_newline(src):
    """These pages are CRLF on disk. A generated block with bare LF would show
    up as noise in every future diff, so match whatever the file already uses."""
    crlf = src.count("\r\n")
    return "\r\n" if crlf > (src.count("\n") - crlf) else "\n"


def block_for(page, title, desc, url, nl):
    img = "%s/%s" % (SITE, IMG_BY_PAGE.get(page, IMG_DEFAULT))
    tags = [
        ("property", "og:type", "website"),
        ("property", "og:site_name", "Target Digital"),
        ("property", "og:locale", "en_AU"),
        ("property", "og:url", url),
        ("property", "og:title", title),
        ("property", "og:description", desc),
        ("property", "og:image", img),
        ("property", "og:image:width", IMG_W),
        ("property", "og:image:height", IMG_H),
        ("property", "og:image:alt", "Target Digital AI"),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", title),
        ("name", "twitter:description", desc),
        ("name", "twitter:image", img),
    ]
    lines = [START]
    for attr, key, val in tags:
        lines.append('<meta %s="%s" content="%s">' % (attr, key, val))
    lines.append(END)
    return nl.join(lines)


def main():
    check = "--check" in sys.argv
    pages = sorted(glob.glob("*.html"))
    stale, wrote = [], []

    for page in pages:
        src = io.open(page, encoding="utf-8", newline="").read()
        vals = extract(src, page)
        if not vals:
            stale.append(page)
            continue

        nl = dominant_newline(src)
        block = block_for(page, vals[0], vals[1], vals[2], nl)

        existing = re.search(re.escape(START) + r".*?" + re.escape(END), src, re.S)
        if existing:
            if existing.group(0) == block:
                continue
            new = src[:existing.start()] + block + src[existing.end():]
        else:
            # Anchor immediately after the canonical, which every page has.
            anchor = re.search(r'<link\s+rel="canonical"[^>]*>', src)
            new = src[:anchor.end()] + nl + block + src[anchor.end():]

        stale.append(page)
        if not check:
            io.open(page, "w", encoding="utf-8", newline="").write(new)
            wrote.append(page)

    if check:
        if stale:
            print("FAIL: %d page(s) missing or stale OG tags:" % len(stale))
            for p in stale:
                print("  - %s" % p)
            return 1
        print("OK: OG + twitter:card present and current on all %d pages." % len(pages))
        return 0

    print("OG tags installed/refreshed on %d of %d pages." % (len(wrote), len(pages)))
    for p in wrote:
        print("  + %s" % p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
