#!/usr/bin/env python3
"""Install (or refresh) the delegated GA4 event tracker on every page.

The base gtag snippet lives in <head> and only measures page views. This adds
one delegated click/submit listener per page so every button, CTA, nav link,
phone/email link, FAQ toggle, demo form and calculator step reports to GA4.

Why delegation instead of onclick="gtag(...)" on each element:
  - update_nav.py rewrites the nav on every page; per-element handlers there
    would be wiped on the next run.
  - ~120 CTAs across 14 pages is 120 chances to typo an event name.
  - New buttons are tracked automatically the moment they're added.

Idempotent: re-running replaces the existing block instead of stacking a
second copy (the update_nav.py double-injection trap).

    PYTHONIOENCODING=utf-8 PYTHONUTF8=1 py add_ga4_events.py
    PYTHONIOENCODING=utf-8 PYTHONUTF8=1 py add_ga4_events.py --check   # verify only
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Discovered, not hardcoded — same rule check_site.py uses. A hardcoded list
# would silently leave the next new page untracked.
PAGES = [p.name for p in sorted(ROOT.glob("*.html"))]

START = "<!-- ga4-events:start — generated by add_ga4_events.py; edit the script, not this block -->"
END = "<!-- ga4-events:end -->"

TRACKER = START + """
<script>
(function () {
  'use strict';

  // ── Event map ────────────────────────────────────────────────────────────
  // generate_lead     Calendly click or calculator email unlock. THE conversion.
  //                   Mark this as a Key Event in GA4 → Admin → Events.
  // cta_click         Any other internal CTA/link (demo hub, cross-sell, magnets)
  // nav_click         Header or mobile-menu navigation
  // contact_click     tel: / mailto: links  (param: method = phone | email)
  // demo_start        A live demo form was submitted (param: demo_name)
  // calculator_submit The ROI calculator was run
  // faq_click         An FAQ question was clicked (param: expanded = open | closed)
  //
  // Every event also carries: cta_text, cta_location, page_id.
  // cta_location is the nearest landmark — 'nav', 'mobile_nav', 'footer', or
  // the enclosing <section id>, e.g. 'hero' / 'pricing' / 'cta-final' — so the
  // same "Book a Call" label can be told apart by where on the page it sits.

  var CALENDLY = 'calendly.com';

  var DEMO_FORMS = {
    leadForm: 'lead_qualification',
    callForm: 'outbound_call',
    invForm: 'invoice_automation',
    docForm: 'document_automation'
  };

  function ev(name, params) {
    if (typeof window.gtag === 'function') window.gtag('event', name, params);
  }

  function label(el) {
    var t = (el.innerText || el.textContent || el.value || '').replace(/\\s+/g, ' ').trim();
    if (t) return t.slice(0, 100);
    return el.getAttribute('aria-label') || el.id || 'unlabelled';
  }

  function pageId() {
    var file = (location.pathname.split('/').pop() || 'index.html').replace(/\\.html$/, '');
    return file || 'index';
  }

  function place(el) {
    var n = el;
    while (n && n !== document.body) {
      if (n.id === 'mobileNav') return 'mobile_nav';
      var tag = n.tagName ? n.tagName.toLowerCase() : '';
      if (tag === 'nav') return 'nav';
      if (tag === 'footer') return 'footer';
      if (tag === 'section' && n.id) return n.id;
      n = n.parentElement;
    }
    return 'body';
  }

  function base(el, extra) {
    var p = { cta_text: label(el), cta_location: place(el), page_id: pageId() };
    if (extra) for (var k in extra) if (extra.hasOwnProperty(k)) p[k] = extra[k];
    return p;
  }

  document.addEventListener('click', function (e) {
    var el = e.target && e.target.closest ? e.target.closest('a, button') : null;
    if (!el) return;

    if (el.tagName === 'BUTTON') {
      // Report EVERY faq-q click, and read the resulting state into a param
      // rather than gating the event on it. The accordion's open/close class is
      // set by a page script that shares a <script> block with the Lenis/GSAP
      // CDN init — if that CDN is blocked or slow, the accordion never binds.
      // Gating on the class would then kill FAQ tracking silently. This way the
      // click is always counted, and an all-'closed' report is itself the
      // signal that the accordion broke for real visitors.
      if (el.classList.contains('faq-q')) {
        var item = el.parentElement;
        ev('faq_click', base(el, {
          expanded: item && item.classList.contains('open') ? 'open' : 'closed'
        }));
      }
      // Submit buttons are reported by the submit listener below, which also
      // catches Enter-key submissions. Nothing more to do here.
      return;
    }

    var href = el.getAttribute('href') || '';

    if (href.indexOf(CALENDLY) !== -1) {
      ev('generate_lead', base(el, { method: 'calendly', link_url: href }));
      return;
    }
    if (href.indexOf('tel:') === 0) {
      ev('contact_click', base(el, { method: 'phone', link_url: href }));
      return;
    }
    if (href.indexOf('mailto:') === 0) {
      ev('contact_click', base(el, { method: 'email', link_url: href }));
      return;
    }
    // In-page anchors and href="#" JS hooks aren't destinations — skip the noise.
    if (href === '' || href.charAt(0) === '#') return;

    var where = place(el);
    ev(where === 'nav' || where === 'mobile_nav' ? 'nav_click' : 'cta_click',
       base(el, { link_url: href }));
  });

  document.addEventListener('submit', function (e) {
    var form = e.target;
    if (!form || !form.id) return;

    if (DEMO_FORMS[form.id]) {
      ev('demo_start', { demo_name: DEMO_FORMS[form.id], page_id: pageId() });
      return;
    }
    if (form.id === 'ltc-form') {
      ev('calculator_submit', { page_id: pageId() });
      return;
    }
    // The email gate: they hand over a name + work email to see the annual
    // number. That is a captured lead, same tier as a Calendly booking.
    if (form.id === 'ltc-unlock') {
      ev('generate_lead', { method: 'calculator_email_gate', page_id: pageId() });
    }
  });
})();
</script>
""" + END

BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)


def apply(path: Path, check_only: bool) -> str:
    """Return one of: 'missing', 'stale', 'ok', 'added', 'refreshed'."""
    html = path.read_text(encoding="utf-8")

    if BLOCK_RE.search(html):
        if BLOCK_RE.search(html).group(0) == TRACKER:
            return "ok"
        if check_only:
            return "stale"
        path.write_text(BLOCK_RE.sub(lambda _: TRACKER, html, count=1), encoding="utf-8")
        return "refreshed"

    if check_only:
        return "missing"

    if "</body>" not in html:
        raise SystemExit(f"FAIL {path.name}: no </body> to inject before")

    # Last </body> only, so a literal '</body>' inside page copy can't misplace it.
    idx = html.rfind("</body>")
    path.write_text(html[:idx] + TRACKER + "\n" + html[idx:], encoding="utf-8")
    return "added"


def main() -> int:
    check_only = "--check" in sys.argv
    bad = 0
    if not PAGES:
        print("FAIL: no .html pages found")
        return 1

    for name in PAGES:
        state = apply(ROOT / name, check_only)
        print(f"  {state:<10} {name}")
        if check_only and state != "ok":
            bad += 1

    # The tracker is inert without the base gtag snippet — verify both are present.
    for name in PAGES:
        if "googletagmanager.com/gtag/js" not in (ROOT / name).read_text(encoding="utf-8"):
            print(f"FAIL {name}: tracker installed but the base gtag snippet is missing")
            bad += 1

    if bad:
        print(f"\n{bad} problem(s).")
        return 1
    print(f"\nGA4 event tracking present on all {len(PAGES)} pages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
